runtime: nodejs16  # or another supported version
service: gcp-booster-client
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$


  - url: /.*
    static_files: build/index.html
    upload: build/index.html